### PR TITLE
Rspec testing

### PR DESCRIPTION
**Pull request by Qoosim**
This PR consists of possible functionalities of some Enumerable methods

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

- Set up Stickler to lint the code in your project, find out more about how to do that in [here](https://github.com/microverseinc/linters-config).

- Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by Redvanisation** [comment]
Sorry guys I meant setup stickler to lint your code and not your CSS.

**Review by Redvanisation — APPROVED** [review]
# Project approved ✔️ 

### Hello team 🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Comment by Qoosim** [comment]
That has been fixed

**Pull request merged**
